
export const reducerCases = {
    SET_USER_INFO: "SET_USER_INFO",
    SET_NEW_USER: "SET_NEW_USER",
    SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
    SET_CURRENT_CHAT_USER: "SET_CURRENT_CHAT_USER",
    SET_MESSAGES: "SET_MESSAGES",
    SET_SOCKET: "SET_SOCKET",
    ADD_MESSAGE: "ADD_MESSAGE",
    UPDATE_MESSAGE: "UPDATE_MESSAGE",
    REMOVE_MESSAGE: "REMOVE_MESSAGE",
    SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
    SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
    SET_SEARCH_INDEX: "SET_SEARCH_INDEX",
    // call actions
    START_CALL: "START_CALL",
    CLEAR_OUTGOING_CALL: "CLEAR_OUTGOING_CALL",
    SET_INCOMING_CALL: "SET_INCOMING_CALL",
    CLEAR_INCOMING_CALL: "CLEAR_INCOMING_CALL",
    END_CALL: "END_CALL",
}